language: python

sudo: enabled

python:
  - 3.6

os:
  - linux

env:
  global:
    - TORCH_VERSION=1.4.0
  jobs:
    - FORCE_CUDA=0 TORCH=1.4.0+cpu
    - FORCE_CUDA=1 CUDA=9.2.148-1 CUDA_SHORT=9.2 UBUNTU_VERSION=ubuntu1604 CUBLAS=cuda-cublas-dev-9-2 TORCH=${TORCH_VERSION}+cu92
    - FORCE_CUDA=1 CUDA=10.0.130-1 CUDA_SHORT=10.0 UBUNTU_VERSION=ubuntu1804 CUBLAS=cuda-cublas-dev-10-0 TORCH=${TORCH_VERSION}+cu100
    - FORCE_CUDA=1 CUDA=10.1.105-1 CUDA_SHORT=10.1 UBUNTU_VERSION=ubuntu1804 CUBLAS=libcublas-dev TORCH=${TORCH_VERSION}

before_install:
  - bash install.sh

install:
  - pip install numpy
  - pip install torch==${TORCH} -f https://download.pytorch.org/whl/torch_stable.html
  - python -c "import torch; print(torch.__version__)"
  - pip install flake8

script:
  - flake8 .
  - python setup.py install
  - python setup.py test
notifications:
  email: false
