language: python

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - name: cu92
      env:
        - FORCE_CUDA=1
        - CUDA=9.2.148-1
        - CUDA_SHORT=9.2
        - UBUNTU_VERSION=ubuntu1604
    - name: cu100
      env:
        - FORCE_CUDA=1
        - CUDA=10.0.130-1
        - CUDA_SHORT=10.0
        - UBUNTU_VERSION=ubuntu1804
    - name: cu101
      env:
        - FORCE_CUDA=1
        - CUDA=10.1.105-1
        - CUDA_SHORT=10.1
        - UBUNTU_VERSION=ubuntu1804

before_install:
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-} cuda-cusparse-dev-${CUDA_SHORT/./-}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}

install:
  - pip install numpy
  - pip install torch==1.4.0+cu${CUDA_SHORT/./} -f https://download.pytorch.org/whl/torch_stable.html

script:
  - nvcc --version
  - python -c "import torch; print(torch.__version__)"
  - python setup.py install
  - python setup.py test
