sudo: enabled

env:
  global:
    - TORCH_VERSION=1.4.0
  # jobs:
  #   - FORCE_CUDA=0 TORCH=${TORCH_VERSION}+cpu
  #   - FORCE_CUDA=1 CUDA_SHORT=9.2 CUDA=9.2.148-1 UBUNTU_VERSION=ubuntu1604 CUBLAS=cuda-cublas-dev-9-2 TORCH=${TORCH_VERSION}+cu92
    # - FORCE_CUDA=1 CUDA_SHORT=10.0 CUDA=10.0.130-1 UBUNTU_VERSION=ubuntu1804 CUBLAS=cuda-cublas-dev-10-0 TORCH=${TORCH_VERSION}+cu100

jobs:
  include:
    - name: linux/cpu
      os: linux
      language: python
      python: 3.7.6
      env:
        - TORCH=${TORCH_VERSION}+cpu
    - name: linux/cu92
      os: linux
      language: python
      python: 3.7.6
      env:
        - FORCE_CUDA=1
        - CUDA_SHORT=9.2
        - CUDA=9.2.148-1
        - UBUNTU_VERSION=ubuntu1604
        - CUBLAS=cuda-cublas-dev-9-2
        - TORCH=${TORCH_VERSION}+cu92
    - name: linux/cu100
      os: linux
      language: python
      python: 3.7.6
      env:
        - FORCE_CUDA=1
        - CUDA_SHORT=10.0
        - CUDA=10.0.130-1
        - UBUNTU_VERSION=ubuntu1804
        - CUBLAS=cuda-cublas-dev-10-0
        - TORCH=${TORCH_VERSION}+cu100
    - name: linux/cu101
      os: linux
      language: python
      python: 3.7.6
      env:
        - FORCE_CUDA=1
        - CUDA_SHORT=10.1
        - CUDA=10.1.105-1
        - UBUNTU_VERSION=ubuntu1804
        - CUBLAS=libcublas-dev
        - TORCH=${TORCH_VERSION}
    - name: macosx/cpu
      os: osx
      osx_image: xcode11.3
      language: shell
      env:
        - TORCH=${TORCH_VERSION}
    - name: windows/cpu
      os: windows
      language: shell
      env:
        - TORCH=${TORCH_VERSION}+cpu
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version 3.7.6
    # - name: windows/cu92
    #   os: windows
    #   language: shell
    #   env:
    #     - FORCE_CUDA=1
    #     - CUDA_SHORT=9.2
    #     - CUDA=9.2.148
    #     - TORCH=${TORCH_VERSION}+92
    #     - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   before_install:
    #     - choco install python --version 3.7.6
    # - name: windows/cu100
    #   os: windows
    #   language: shell
    #   env:
    #     - FORCE_CUDA=1
    #     - CUDA_SHORT=10.1
    #     - CUDA=10.0.130_411.31
    #     - TORCH=${TORCH_VERSION}+100
    #     - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   before_install:
    #     - choco install python --version 3.7.6
    # - name: windows/cu102
    #   os: windows
    #   language: shell
    #   env:
    #     - FORCE_CUDA=1
    #     - CUDA_SHORT=10.1
    #     - CUDA=10.1.105_418.96
    #     - TORCH=${TORCH_VERSION}
    #     - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   before_install:
    #     - choco install python --version 3.7.6

install:
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then echo "wadawd"; alias python3=python; fi
  - source install.sh
  - pip3 install numpy
  - pip3 install torch==${TORCH} -f https://download.pytorch.org/whl/torch_stable.html
  - pip3 install flake8
  - python3 setup.py install || python setup.py install

script:
  - flake8 .
  - python3 setup.py test || python setup.py test
  - python3 setup.py bdist_wheel || python setup.py bdist_wheel
  # - ls dist
notifications:
  email: false
