language: shell

env:
  global:
    - TORCH_VERSION=1.4.0
    - CUDA_HOME=/usr/local/cuda
  # jobs:
  #   - FORCE_CUDA=0 TORCH=${TORCH_VERSION}+cpu
  #   - FORCE_CUDA=1 CUDA_SHORT=9.2 CUDA=9.2.148-1 UBUNTU_VERSION=ubuntu1604 CUBLAS=cuda-cublas-dev-9-2 TORCH=${TORCH_VERSION}+cu92
    # - FORCE_CUDA=1 CUDA_SHORT=10.0 CUDA=10.0.130-1 UBUNTU_VERSION=ubuntu1804 CUBLAS=cuda-cublas-dev-10-0 TORCH=${TORCH_VERSION}+cu100

jobs:
  include:
    - name: linux/cpu
      os: linux
      env:
        - IDX = cpu
        - TOOLKIT=cpuonly
    - name: linux/cu92
      os: linux
      env:
        - IDX=cu92
        - CUDA_SHORT=9.2
        - CUDA=9.2.148-1
        - UBUNTU_VERSION=ubuntu1604
        - CUBLAS=cuda-cublas-dev-9-2
        - TOOLKIT="cudatoolkit=${CUDA_SHORT}"
    - name: linux/cu100
      os: linux
      env:
        - IDX=cu100
        - CUDA_SHORT=10.0
        - CUDA=10.0.130-1
        - UBUNTU_VERSION=ubuntu1804
        - CUBLAS=cuda-cublas-dev-10-0
        - TOOLKIT="cudatoolkit=${CUDA_SHORT}"
    - name: linux/cu101
      os: linux
      env:
        - IDX=cu101
        - CUDA_SHORT=10.1
        - CUDA=10.1.105-1
        - UBUNTU_VERSION=ubuntu1804
        - CUBLAS=libcublas-dev
        - TOOLKIT="cudatoolkit=${CUDA_SHORT}"
    # - name: macosx/cpu
    #   os: osx
    #   osx_image: xcode11.3
    #   language: shell
    #   env:
    #     - IDX=cpu
    #     - TORCH=${TORCH_VERSION}
    # - name: windows/cpu
    #   os: windows
    #   language: shell
    #   env:
    #     - IDX=cpu
    #     - TORCH=${TORCH_VERSION}+${IDX}
    #     - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   before_install:
    #     - choco install python --version 3.7.6
    #     - python -m pip install --upgrade --user pip
    # - name: windows/cu92
    #   os: windows
    #   language: shell
    #   env:
    #     - IDX=cu92
    #     - CUDA_SHORT=9.2
    #     - CUDA=9.2.148
    #     - TORCH=${TORCH_VERSION}+${IDX}
    #     - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   before_install:
    #     - choco install python --version 3.7.6
    #     - python -m pip install --upgrade --user pip
    # - name: windows/cu100
    #   os: windows
    #   language: shell
    #   env:
    #     - FORCE_CUDA=1
    #     - CUDA_SHORT=10.1
    #     - CUDA=10.0.130_411.31
    #     - TORCH=${TORCH_VERSION}+100
    #     - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   before_install:
    #     - choco install python --version 3.7.6
    # - name: windows/cu102
    #   os: windows
    #   language: shell
    #   env:
    #     - FORCE_CUDA=1
    #     - CUDA_SHORT=10.1
    #     - CUDA=10.1.105_418.96
    #     - TORCH=${TORCH_VERSION}
    #     - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    #   before_install:
    #     - choco install python --version 3.7.6

install:
  # - source script/install.sh
  - source script/conda.sh
  - conda create --yes -n test python=3.7.6
  - source activate test
  - conda install pytorch=${TORCH_VERSION} ${TOOLKIT} -c pytorch --yes
  - pip install flake8
  - pip install codecov
  - python setup.py install
  # - pip3 install --upgrade pip
  # - pip3 install wheel
  # - pip3 install numpy
  # - pip3 install torch==${TORCH} -f https://download.pytorch.org/whl/torch_stable.html

script:
  - flake8 .
  - python setup.py test
after_success:
  - python setup.py bdist_wheel --dist-dir=dist/torch-${TORCH_VERSION}/${IDX}
  - codecov
deploy:
  provider: s3
  edge: true
  access_key_id: AKIAJB7S6NJ5OM5MAAGA
  secret_access_key: ${S3_SECRET_ACCESS_KEY}
  bucket: pytorch-scatter
  local_dir: dist/torch-${TORCH_VERSION}/${IDX}
  upload_dir: whl/torch-${TORCH_VERSION}/${IDX}
  acl: public_read
  on:
    repo: rusty1s/pytorch_scatter
    # tags: true
    branch: travis
notifications:
  email: false
