language: shell

os:
  # - linux
  # - osx
  - windows

env:
  global:
    - CUDA_HOME=/usr/local/cuda
  jobs:
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8.1 IDX=cpu
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8.1 IDX=cu92
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8.1 IDX=cu100
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8.1 IDX=cu101
    - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.7.6 IDX=cpu
    - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.7.6 IDX=cu92
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.7.6 IDX=cu100
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.7.6 IDX=cu101
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.6.10 IDX=cpu
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.6.10 IDX=cu92
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.6.10 IDX=cu100
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.6.10 IDX=cu101
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.5.9 IDX=cpu
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.5.9 IDX=cu92
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.5.9 IDX=cu100
    # - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.5.9 IDX=cu101

jobs:
  exclude:
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8.1 IDX=cu92
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8.1 IDX=cu100
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8.1 IDX=cu101
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.7.6 IDX=cu92
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.7.6 IDX=cu100
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.7.6 IDX=cu101
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.6.10 IDX=cu92
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.6.10 IDX=cu100
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.6.10 IDX=cu101
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.5.9 IDX=cu92
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.5.9 IDX=cu100
    - os: osx
      env: TORCH_VERSION=1.4.0 PYTHON_VERSION=3.5.9 IDX=cu101

install:
  - source script/cuda.sh
  - source script/conda.sh
  - conda create --yes -n test python=${PYTHON_VERSION}
  - source activate test
  - conda install pytorch=${TORCH_VERSION} ${TOOLKIT} -c pytorch --yes
  - pip install flake8 codecov
  - python setup.py install

script:
  - flake8 .
  - python setup.py test
after_success:
  - python setup.py bdist_wheel --dist-dir=dist/torch-${TORCH_VERSION}/${IDX}
  - codecov
deploy:
  provider: s3
  region: eu-central-1
  edge: true
  access_key_id: AKIAJB7S6NJ5OM5MAAGA
  secret_access_key: ${S3_SECRET_ACCESS_KEY}
  bucket: pytorch-scatter
  local_dir: dist/torch-${TORCH_VERSION}/${IDX}
  upload_dir: whl/torch-${TORCH_VERSION}/${IDX}
  acl: public_read
  on:
    repo: rusty1s/pytorch_scatter
    # tags: true
    branch: travis
notifications:
  email: false
