language: python

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - name: Linux/CUDA 9.2
      env:
        - FORCE_CUDA=1
        - CUDA=9.2.148-1
        - CUDA_SHORT=9.2
        - UBUNTU_VERSION=ubuntu1604

before_install:
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-${CUDA_SHORT/./-} 
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}

install:
  - pip install numpy
  - pip install torch==1.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

script:
  - nvcc --version
  - python -c "import torch; print(torch.__version__)"
  - ls /usr/local/
  - ls /usr/local/cuda-${CUDA_SHORT}
  - ls /usr/local/cuda-${CUDA_SHORT}/lib64
  - ls /usr/local/cuda-${CUDA_SHORT}/include
  - python setup.py install
  - python setup.py test
