name: "Close stale issues and PRs"

on:
  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue had no activity for **6 months**. It will be closed in **2 weeks** unless there is some new activity.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug,enhancement,Priority P0,Priority P1,Priority P2'
          stale-pr-message: 'This pull request had no activity for **6 months**. It will be closed in **2 weeks** unless there is some new activity.'
          stale-pr-label: 'stale'
          days-before-stale: 180
          days-before-close: 14
